### ISSUE TITLE
Build is failing!

### ISSUE THREAD

**Issue by samarpanda** [bensmithett/webpack-css-example#4]
## Build is failing!

`npm run build` is failing. Attaching the terminal log:

```shell
npm run build

> webpack-css-example@1.0.0 build /Users/samar/Projects/learn-webpack/webpack-css-example
> webpack

Hash: 191467eb0d73dca00856
Version: webpack 1.12.2
Time: 11230ms
 Asset    Size  Chunks             Chunk Names
app.js  609 kB       0  [emitted]  app
   [0] multi app 28 bytes {0} [built]
    + 162 hidden modules

ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
 @ ./src/stylesheets/base.sass 4:14-504

ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
 @ ./src/stylesheets/modules/container.sass 4:14-517

ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
 @ ./src/stylesheets/modules/header.sass 4:14-514

ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
 @ ./src/stylesheets/utilities/clearfix.sass 4:14-518

ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
 @ ./src/stylesheets/modules/footer.sass 4:14-514

ERROR in ./src/stylesheets/base.sass
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:90:22)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:77:5)
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:576:13)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:571:10)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:562:8)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:524:7)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:444:10)
    at Compilation.errorAndCallback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:343:3)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:399:12)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206:13)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)

ERROR in ./src/stylesheets/modules/header.sass
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:90:22)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:77:5)
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:576:13)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:571:10)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:562:8)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:524:7)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:444:10)
    at Compilation.errorAndCallback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:343:3)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:399:12)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206:13)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)

ERROR in ./src/stylesheets/utilities/clearfix.sass
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:90:22)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:77:5)
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:576:13)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:571:10)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:562:8)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:524:7)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:444:10)
    at Compilation.errorAndCallback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:343:3)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:399:12)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206:13)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)

ERROR in ./src/stylesheets/modules/footer.sass
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:90:22)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:77:5)
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:576:13)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:571:10)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:562:8)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:524:7)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:444:10)
    at Compilation.errorAndCallback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:343:3)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:399:12)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206:13)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)

ERROR in ./src/stylesheets/modules/container.sass
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:90:22)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Object.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/extract-text-webpack-plugin/loader.js:77:5)
    at Compiler.next (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:576:13)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:571:10)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:562:8)
    at Compilation.applyPluginsAsync (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:524:7)
    at Compiler.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:444:10)
    at Compilation.errorAndCallback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:343:3)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:399:12)
    at /Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206:13)
    at DependenciesBlock.loadPitch (/Users/samar/Projects/learn-webpack/webpack-css-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
```

**Comment by samarpanda** [comment]
I bumped the version number for `sass-loader` from `0.4.1` to `3.1.1` in `package.json`. Now it seems working. Will add a PR for this.

**Comment by bensmithett** [comment]
@samarpanda hmm, the current version works fine for me. Looks like something went wrong when Sass installed for you. Can you delete `node_modules`, run `npm install` again & see if it all installs correctly? Also which version of node & npm are you using?

**Comment by samarpanda** [comment]
I tried `npm install` removing node_modules completely. No luck there. I am using:
```shell
[samar@sp webpack-css-example [±] master 5b34def ✓]$ node -v
v4.0.0
[samar@sp webpack-css-example [±] master 5b34def ✓]$ npm -v
2.14.2
```

**Comment by bensmithett** [comment]
Ah, I believe older versions of node-sass have some trouble with Node 4. Leave it with me, I'll upgrade a bunch of things at once :smile:

**Comment by samarpanda** [comment]
Cool :satisfied:

**Comment by dbox** [comment]
`"sass-loader": "^3.1.1",` fixed it for me

**Comment by bensmithett** [comment]
Updated all the things & released a new version: https://github.com/bensmithett/webpack-css-example/releases/tag/v2.0.0

Thanks for letting me know @samarpanda! Shout out if you have any more issues.

**Comment by samarpanda** [comment]
Cool @bensmithett. Thanks for the quick release. :+1:
